2024-11-17 06:13:25,797 [INFO] Loading data...
2024-11-17 06:13:25,835 [INFO] Loaded 1459 keywords and 200 hyperedges
2024-11-17 06:13:26,413 [INFO] Starting training...
2024-11-17 06:13:26,849 [ERROR] An error occurred: mat1 and mat2 shapes cannot be multiplied (32x128 and 256x128)
Traceback (most recent call last):
  File "main.py", line 144, in main
    train_history = trainer.train(
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\trainer.py", line 173, in train
    losses = self.train_epoch(
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\trainer.py", line 70, in train_epoch
    losses = self._compute_losses(x, edge_index, pos_pairs, neg_pairs)
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\trainer.py", line 96, in _compute_losses
    prediction_loss = self._compute_prediction_loss(embeddings, pos_pairs, neg_pairs)
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\trainer.py", line 125, in _compute_prediction_loss
    pos_scores = self.predictor(pos_features).squeeze(-1)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\model.py", line 244, in forward
    return self.mlp(node_features)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\container.py", line 219, in forward
    input = module(input)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x128 and 256x128)
